### ISSUE TITLE
BUG: Invisible item selection

### ISSUE THREAD

**Issue by Catomax262** [Lightman314/LightmansCurrency#108]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Lightman's Currency Version

2.0.0.6

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

none

### Describe the bug

For some reason, i can't select items for purchase.
![2022-12-16_02 07 30](https://user-images.githubusercontent.com/80112576/208042707-de035a19-2708-49d4-b32c-e58314d9335b.png)
Playing with the es_es language. You can still interact with the selection but you can't see any of the items.

### To Reproduce

1. Get any trading machine
2. Select the item box
3. Select the "sale" mode
4. There should be no item selection. On the "purchase" mode the selection appears as normal.

### Screenshots/Logs/Crash Reports

it doesn't affect the log

**Comment by Guda-nemo** [comment]
It's better to be fixed in the future but you can also drop the items on the slot to select them instead.

**Comment by Lightman314** [comment]
As noted in the changelog of v2.0.0.0:
`Item Edit/Selection widget no longer appears when selecting a sell item, as if you're selling something it's assumed you'll have it on hand.`

The item selection widget being hidden for sale item selection is 100% intentional, as certain players were getting issues where items couldn't be put in storage due to invisible/hidden nbt data differences from their creative tab counterpart (such as an Unbreaking 3 book created in an anvil from 2 Unbreaking 2 books having repair data, whereas the Unbreaking 3 book from creative having no such data). The widget will still show in situations where you may not and are not required to actually have the item (such as selecting the item(s) to purchase and/or barter for).

Placing the items in the slot has **always** been the intended method of defining a trades items, as it's more convenient for everyone involved (as you can do it from the main storage tab without having to open every single trade individually). The item selection widget is there **solely** for the purpose of being able to buy or barter for items that you don't actually have the capability of obtaining (i.e. you happened upon or were gifted a bunch of money, and you really want a beacon, but you can't exactly kill a wither with only your stone starter gear, so you set up a trader to buy a nether star/beacon).
