### ISSUE TITLE
1.18 Atm eating money on exit

### ISSUE THREAD

**Issue by Epicsmel** [Lightman314/LightmansCurrency#12]
When exiting the atm in 1.18 any money left in the atm will not be returned to the player and is deleted. 

In 1.16.5 this works as intended and coins are returned. I tested with just the mod on its own in 1.18 and 1.16.5.

**Comment by Lightman314** [comment]
So it doesn't.... fixed in v1.18-1.0.1.3a. It appears something went wrong when I ported this menu to 1.18, as this was the only menu that didn't have a block entity attached and the 1.16 handled them slightly differently than 1.18 does. I'll likely also have to fix this on the 1.17 version as well.
