### ISSUE TITLE
BUG: Wallet wont open

### ISSUE THREAD

**Issue by Dapper-Fox** [Lightman314/LightmansCurrency#122]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Lightman's Currency Version

2.1.1.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Whenever i tried to open my wallet it imediatly closed

### To Reproduce

go to an aternos server (idk if the kind of server matters)
get a wallet and equip
try to open

### Screenshots/Logs/Crash Reports

idk how to screenshot an active bug that takes 2 frames and it didnt crash

**Comment by Lightman314** [comment]
Works fine for me (testing done on a server as well)
![image](https://user-images.githubusercontent.com/4554273/229393219-b919902b-fb9e-42b4-96c9-93dfa6b33588.png)
![image](https://user-images.githubusercontent.com/4554273/229393197-8427fc64-3be5-42a0-8c78-1d46d4af253f.png)

Unable to replicate. Please provide the latest.log file from both the client and the server (as is requested in the Screenshots/Logs section of the report), so that I can inspect them for error messages or other useful information.

**Comment by Lightman314** [comment]
If no response is received by April 10th, this issue will be closed due to a lack of requested info and my inability to duplicate.

**Comment by Dapper-Fox** [comment]
> If no response is received by April 10th, this issue will be closed due to a lack of requested info and my inability to duplicate.

well it is still broken for me, if you want i can send you the pack im using so that you can have more information?

**Comment by Lightman314** [comment]
Or you could just give me the logs I requested in my previous comment...

**Comment by Dapper-Fox** [comment]
> Or you could just give me the logs I requested in my previous comment...

there are no logs, as there was no crash

**Comment by Lightman314** [comment]
> there are no logs, as there was no crash

latest.log files are generated every time you launch the game on both the server and the client (and are located in your `logs/` folder) and contain **important** debug information, and/or safely caught errors that I **need** in order to figure out what it going wrong.

Logs are not crash reports, but are just as useful for tracking down the cause of issues like this.
