### ISSUE TITLE
BUG: Client config doesn't appear on my Aternos server

### ISSUE THREAD

**Issue by PsydameousSharm** [Lightman314/LightmansCurrency#123]
### Minecraft Version

1.19.4

### Forge Version

45.0.43

### Lightman's Currency Version

2.1.1.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Configured v2.1.1

### Describe the bug

I wanted to change on my Aternos server,the value to make me able to turn coins back into materials with the minting machine, but on my folder, via website, the client folder isn't there. Just, "lightmans_currency" and "lightmans_currency_common" I also have the Configured mod, and though there is a client one, I couldn't find anything about minting, nor could I find it in my folder. Is there something I'm missing?

### To Reproduce

Get an Aternos server
Set the platform to forge 1.19.4
Install Lightman's currency
Open forge
Make a new profile with Lightman's currency and Configured on 1.19.4
proceed to look through all apparent config folders.

### Screenshots/Logs/Crash Reports

<img width="1019" alt="Screenshot 2023-04-07 at 11 01 13 AM" src="https://user-images.githubusercontent.com/128945100/230655830-b29079ef-ae2b-468f-888a-1d88c82f3182.png">

**Comment by Lightman314** [comment]
First off, the config options about minting/melting are on the _server_ config, not the _client_ config. See the [wiki](https://github.com/Lightman314/LightmansCurrency/wiki/Mod-Configuration)  for more details on their locations, etc.

Another note, dedicated servers do not create or load client config files, as is dictated by minecraft forge itself. The reason for this is that client config options are only relevant for minecraft clients, not servers, and thus contain config options about rendering, etc.

**Comment by PsydameousSharm** [comment]
Okay, I looked, and it did say I could melt down coins, but when I try to, it doesn't go into either slot of the coin minter. Is there something I'm doing wrong?

**Comment by Lightman314** [comment]
Did you enable it in the server config that I linked you the wiki page for in my previous comment?
Or, you know, read the wiki and/or the FAQ at all?

**Comment by PsydameousSharm** [comment]
Honestly, I can set up an exchange shop, but by GOD, are you rude! Making my friends happy is the only thing keeping me from uninstalling your mod due to your behavior. I hope I never meet you because you seem like a jerk. I hope you consider why you were such a trash head to genuine questions and how you should be kinder to people.

**Comment by Lightman314** [comment]
I'm sorry if that came across as rude, but I literally gave you a link to a resource explaining in excruciating detail on how you can configure every little aspect of my mod (which took quite a while to make btw), and instead of using it when prompted, you instead ignore my multiple attempts to direct you towards it, and instead respond with "yeah, you say it can be done" without actually doing any of your own research.

I have a million things to do, and I'd rather be spending my time actually focusing on how to improve my mod (or its documentation/wiki) instead of answering questions that I've literally already told you the answer to, given you all the resources you need to figure it out for yourself, and yet you still refuse to actually use them.

If you had questions about them, or they were unclear and you had follow-up questions that'd be one thing, but you clearly aren't even _attempting_ to figure out the actual method of doing this, so you'll get no more help from me, aside from one more link to the answer you seek:

https://github.com/Lightman314/LightmansCurrency/wiki/Mod-Configuration

There! The answer I gave you in my literal first comment! I've now pointed you to it 3 times, so if you can't figure it out from here, I'm afraid you're on your own buddy.
