### ISSUE TITLE
Game crashing bug

### ISSUE THREAD

**Issue by Chromeyay** [Lightman314/LightmansCurrency#13]
![image](https://user-images.githubusercontent.com/82741859/147801654-f084f3cb-f52d-4e05-8aa8-4c5eaafb8de7.png)
[crashreport.txt](https://github.com/Lightman314/LightmansCurrency/files/7795262/crashreport.txt)

**Comment by Lightman314** [comment]
I honestly have no clue how this happened, as it appears as though the players somehow managed to equip a coin into the wallet slot. I'll add some checks in the code to throw an error message in the logs when this happens in the future instead of crashing, but unless you have any additional context as to how a coin managed to be equipped into the wallet slot that's the best I can do.

**Comment by Chromeyay** [comment]
When you mean a coin was equipped in the wallet slot, do you mean a coin is able to be placed in the slot that has the wallet icon? I shift clicked a stack of coins and it went straight into that slot first.

**Comment by Lightman314** [comment]
Yes, coins should not be able to be placed into the slot with the wallet icons. Only wallets can go there.

**Comment by Lightman314** [comment]
Fixed in v1.0.1.6. The coins will likely remain in the wallet slot, but it shouldn't cause any crashes. You should be able to remove the coins from the wallet slot and put them in the wallet as normal.

I'll update the wiki tomorrow as well to show how the new wallet screen works, as it's a somewhat new design since I added the wallet equip/unequip functionality to it only 2 versions ago.
