### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by petiuka** [Lightman314/LightmansCurrency#131]
### Minecraft Version

1.19.4

### Forge Version

45.1.0

### Lightman's Currency Version

2.1.1.5

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Im getting crash on clientside when im playing on server with this mod when im trying to change prices of item in shop
![image](https://github.com/Lightman314/LightmansCurrency/assets/86064499/09a2a774-d83a-4748-a5e4-d42c8961d737)

more info here - https://crashy.net/13c0d389-38c1-4ccf-9068-5910f672cef8

### To Reproduce

1. Join server with that mod
2. Try to change item price in an shop thing
3. Get crashed (only on clientside)

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrency/assets/86064499/09a2a774-d83a-4748-a5e4-d42c8961d737)
more info here - https://crashy.net/13c0d389-38c1-4ccf-9068-5910f672cef8

**Comment by Lightman314** [comment]
Might I request the latest.log file from your client when this error happened (found int your installations `logs` folder)? Cause it likely encountered an error initializing the item list that was safely caught and reported, but resulted in this additional error happening when you tried to access the empty list.

Either way I can add a catch to keep these errors from crashing the game, but it would be helpful if you could provide the log so that I can point you in the direction of the other mod that's actually causing the error.

**Comment by Lightman314** [comment]
Update: Should no longer crash in v2.1.1.5a (and 2.1.0.0f for older versions), however the item edit widget will have no items in this case, so I would still like to request the logs so that I can further look into this issue and possible prevent whatever error is happening during item collection from happening.

**Comment by Lightman314** [comment]
If the logs requested are not posted by Monday, I'll assume this issue is abandoned and close the ticket as the crash itself has been fixed.

**Comment by Lightman314** [comment]
Requested info has not been provided for a week since posting, and the crash portion of the issue has been fixed.
Closing the issue as abandoned.
