### ISSUE TITLE
BUG: LCTech recipe and ATM balance

### ISSUE THREAD

**Issue by DankestO** [Lightman314/LightmansCurrency#136]
### Minecraft Version

1.20.1

### Forge Version

47.1.0

### Lightman's Currency Version

lightmanscurrency-1.20.1-2.1.2.1

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

lctech-1.20.1-0.2.0.0

### Describe the bug

I found two possible errors, one in LCTech with a "fluid trader interface terminal" crafting, there is an item placed with a tag and not as an item.

And another one in Lightsman's currency mod, inside the ATM, the balance is outside the bank, is that normal?
In the transfer tab the balance it's inside ATM so... not sure lol

### To Reproduce

- When searching in JEI for "fluid trader interface terminal"
and
-When using the ATM and going to the Manage account tab

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrency/assets/126206944/65cdd378-e57c-474f-baef-3079bea49cad)
![image](https://github.com/Lightman314/LightmansCurrency/assets/126206944/52abd84c-a675-4628-bb21-3c0d64fd8cef)

**Comment by Lightman314** [comment]
The reason behind the recipe being broken is that I changed the tag for trading terminals from "lightmanscurrency:trading_terminal" to "lightmanscurrency:network_terminal" in the latest LC build, and LC Tech has not yet been updated to account for that.

That said thank you for pointing out the balance text rendering in the wrong position, so I'll make sure that gets fixed in the next bug-fix patch that should (hopefully) be out some time today or tomorrow. I'll probably go ahead and re-add the "trading_terminal" tag as well and have it just inherit the "network_trader" tag for compatibilities sake.

**Comment by DankestO** [comment]
Oh, it's nothing, a pleasure to help, thank to you for this wonderful mod :D
Have a nice day Mr. Lightman

**Comment by Lightman314** [comment]
Fixed in LC v2.1.2.1b/c (patch # is different depending on the MC version)
