### ISSUE TITLE
BUG: Problem with the ATM

### ISSUE THREAD

**Issue by DankestO** [Lightman314/LightmansCurrency#137]
### Minecraft Version

1.19.2

### Forge Version

43.2.21

### Lightman's Currency Version

2.1.0.0f

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Good afternoon, I understand that you no longer update version 1.19.2, but in case of any bug?
I found in the atm the exchange tab shows absolutely nothing, from what I've seen so far, it's just that tab.

(I also found a minor bug, the key to open the wallet is trying to open despite not having a wallet.)

Thanks.

### To Reproduce

1. Just open the ATM menu with right click

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrency/assets/126206944/d523234f-a50d-448d-82b9-a0c13bb94c5a)

**Comment by Lightman314** [comment]
Tested it on that exact version, and it worked just fine for me:
![image](https://github.com/Lightman314/LightmansCurrency/assets/4554273/a9c1c380-c80f-45a7-9fcf-c38b01547d9b)

I'd recommend deleting the `config/lightmanscurrency/ATMData.json` file and see if that fixes your problem. If it does not please provide the latest.log file so that I can search through it whatever error may be causing this.

**Comment by Lightman314** [comment]
Yes, on login (and reload), the server syncs both the ATMData and the MasterCoinList to the clients. That way a server owner can change the coin list, and also force the exchange menu to match their registered coins without having to tell every single player to download and replace their ATMData config.
