### ISSUE TITLE
Feature Request: Add recipe for copper coins pre-1.17

### ISSUE THREAD

**Issue by AlanCretel** [Lightman314/LightmansCurrency#138]
When playing on Minecraft versions before 1.17 there is no recipes for copper coins in the minting machine even when copper ore is added from other mods.

Add the recipe if a copper ore is added to the game (check for registered blocks with the tag forge:ores/copper) ?

**Comment by Lightman314** [comment]
This is impossible, as a recipe cannot define its output based on an item tag (which would need to be done for the recipe to melt a copper coin back into an iron ingot).

Because of this,I have made data packs to add mint/melt recipes for common mods that add copper ingots that can be downloaded [HERE](https://github.com/Lightman314/LightmansCurrency/tree/LC-1.16/Recipe%20Datapacks). This is mentioned on the home page of the Wiki and in the Mod Description, so how you missed this I cannot say.

Another thing of note:
1.16 is no longer supported (as is noted in my mod description), so making a feature request specifically for an unsupported version really should not be done (with the ONLY exception being to request the creation of another copper mint/melt recipe datapack). Reporting crashes or game-breaking issues is fine, but it's fairly set in stone that the 1.16 version will not get updated unless there's something wrong with it that makes it unusable...
