### ISSUE TITLE
BUG: Setting price in display case crash client

### ISSUE THREAD

**Issue by Overtekk** [Lightman314/LightmansCurrency#144]
### Minecraft Version

1.20.1

### Forge Version

47.1.43

### Lightman's Currency Version

lightmanscurrency-1.20.1-2.1.2.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

When trying to setting price for a vending machine it crash the client

### To Reproduce

1. Place a vending machine
2. Access GUI
3. Click on "set price"
4. Freeze and crash

### Screenshots/Logs/Crash Reports

[crash-2023-09-04_18.42.02-client.txt](https://github.com/Lightman314/LightmansCurrency/files/12515379/crash-2023-09-04_18.42.02-client.txt)
[latest.log](https://github.com/Lightman314/LightmansCurrency/files/12515383/latest.log)

**Comment by Lightman314** [comment]
Fixed in 2.1.2.3b.

Should _hopefully_ be fixed for good this time, as I generated a fake error (cause that's what causes these is another mod not having their creative item list ready at an appropriate time) and made sure that failing to generate the items would not cause the Item Edit to crash once opened or interacted with.
