### ISSUE TITLE
BUG: dropping TPS

### ISSUE THREAD

**Issue by BlackDragonCZ** [Lightman314/LightmansCurrency#146]
### Minecraft Version

1.19.2

### Forge Version

43.2.21

### Lightman's Currency Version

2.1.0.0g

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

all current mods are within this modpack: https://www.curseforge.com/minecraft/modpacks/ruinsofindustry

### Describe the bug

Interacting with anything by any player is very slow and almost unplayable.

### To Reproduce

1. place Armor Display
2. put some armor inside
3. wait like 20 minutes
4. game is mostly unplayable because active pinging ID of armor stand from log: [**MessageRequestArmorStandID.lambda$handle$0()**]

### Screenshots/Logs/Crash Reports

https://spark.lucko.me/RQcS7toPp5

**Comment by Lightman314** [comment]
This bug was technically already fixed in v2.1.0.1, however this fix never got applied to the unsupported 1.19.2 or 1.16.5 versions of the mod.

I'll go ahead and apply this fix to 1.19.2 (uploaded as 1.19.2-2.1.0.0h), as it's fairly easy to do so, however I will note that 1.19.2 and 1.16.5 are *unsupported* and as a general rule will not normally receive updates like this unless it's extremely game-breaking, such as an exploit or a crash.
