### ISSUE TITLE
BUG: Where's the ticket button on Paygate

### ISSUE THREAD

**Issue by BigFireTT** [Lightman314/LightmansCurrency#151]
### Minecraft Version

1.18.2

### Forge Version

40.2.9

### Lightman's Currency Version

2.1.2.4

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

I don't have a button to accept tickets on Paygate, but everyone else does.
Maybe it's this mod. I don't know.

![2023-11-03_18-20-17](https://github.com/Lightman314/LightmansCurrency/assets/112418287/89b83df4-2190-4260-b319-94ed4b975b62)

### To Reproduce

1.Place Paygate
2.Open Gui
3.AND WHERES THE HELL TICKETS?

### Screenshots/Logs/Crash Reports

![2023-11-03_18-20-17](https://github.com/Lightman314/LightmansCurrency/assets/112418287/5d3f5fa1-7227-470a-a49e-328363de77be)

**Comment by Lightman314** [comment]
The "collect ticket stub" button only appears if ticket stubs are currently stored, or if you have a trade in the Paygate that is flagged as supposed to store the ticket stubs. (Similar to how the collect money button won't appear if the trader is creative, as there's no need for it when the trader doesn't actually store any money)

Considering that your screenshot shows that no trades are set up for the paygate, I'm assuming that it's not appearing because neither of those requirements are met (as it obviously doesn't spawn with ticket stubs in its inventory, and no trade set up means no trades flagged to store ticket stubs), therefore the button is working as intended.

**Comment by BigFireTT** [comment]
> The "collect ticket stub" button only appears if ticket stubs are currently stored, or if you have a trade in the Paygate that is flagged as supposed to store the ticket stubs. (Similar to how the collect money button won't appear if the trader is creative, as there's no need for it when the trader doesn't actually store any money)
> 
> Considering that your screenshot shows that no trades are set up for the paygate, I'm assuming that it's not appearing because neither of those requirements are met (as it obviously doesn't spawn with ticket stubs in its inventory, and no trade set up means no trades flagged to store ticket stubs), therefore the button is working as intended.



> The "collect ticket stub" button only appears if ticket stubs are currently stored, or if you have a trade in the Paygate that is flagged as supposed to store the ticket stubs. (Similar to how the collect money button won't appear if the trader is creative, as there's no need for it when the trader doesn't actually store any money)
> 
> Considering that your screenshot shows that no trades are set up for the paygate, I'm assuming that it's not appearing because neither of those requirements are met (as it obviously doesn't spawn with ticket stubs in its inventory, and no trade set up means no trades flagged to store ticket stubs), therefore the button is working as intended.

Ive finally found how to activate ticket mode. Anyways, thanks!
