### ISSUE TITLE
Feature Request or bug report? Supplementaries Red Merchant

### ISSUE THREAD

**Issue by AnyankaT** [Lightman314/LightmansCurrency#162]
I'm running LC on my server along with Supplementaries and several other mods. LC recognizes the trader villagers from other mods (Ars Nouveau and Railcraft Reborn) but not the Red Merchant from Supplementaries, and therefore does not replace the trades with currency.

Minecraft 1.20.1
Forge 47.1.43
LC 1.20.1-2.1.2.4b
Supplementaries 1.20-2.7.12

**Comment by Lightman314** [comment]
Unfortunately I don't think this will be possible, as their red merchant trades are hard-coded ([Source](https://github.com/MehVahdJukaar/Supplementaries/blob/1.20/common/src/main/java/net/mehvahdjukaar/supplementaries/common/entities/trades/ModVillagerTrades.java#L43)) instead of registered via forges VillagerTradesEvent. Therefore I have no event to hook into to modify the listings without resorting to mixins, and I'm not sure if you can make a mixin require that another mod be loaded...

**Comment by AnyankaT** [comment]
OK, I'll just have to live with it. Thanks for the info! LOVE the mod!

**Comment by Lightman314** [comment]
Just for grins, I made a feature request with Supplementaries to see if they can add an event I can use.

https://legacy.curseforge.com/minecraft/mc-mods/supplementaries/issues/928

**Comment by Lightman314** [comment]
It would appear that they did add the event I requested, and with it I should be able to modify the trades the same way I do the vanilla and other modded villagers.

I'll do some testing real quick, and if all goes well it should have its trades modified if the config option to modify modded villagers is enabled (with its "profession" being hard-coded as `supplementaries:red_merchant` for use in the `replacementCoinOverrides` config option).

**Comment by Lightman314** [comment]
Update: I've done all that I can on my end, but the event that they added is never called resulting in nothing happening. I'll inform them of this as soon as I can and as soon as they fix that the compatibility should be in place properly on my end in v2.2.0.2!
