### ISSUE TITLE
BUG: Server restart removes currency values from stores

### ISSUE THREAD

**Issue by kiritodragneel** [Lightman314/LightmansCurrency#170]
### Minecraft Version

1.20.1

### Forge Version

47.2.19

### Lightman's Currency Version

2.2.0.0g

**Dev Note**: `Latest` is not a valid Lightman's Currency version. Please correct this.

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

When our server performance a restart any/all stores lose their prices. If i go into a store and change one price then the prices on all other items reloads as well

### To Reproduce

Install
restart server
Issues shows

### Screenshots/Logs/Crash Reports

Would not allow to attach too long

**Comment by kiritodragneel** [comment]
https://pastebin.com/CAPjiEUQ

**Comment by Lightman314** [comment]
Unable to replicate the issue.
Also `Latest` is not a version number, and the logs don't state which version of LC was loaded...

**Comment by gaboemi** [comment]
I second this, happened on a 1.20.1 server, version of the mod being 2.2.0.0g Forge, prices get whipped no matter if its selling or buying, and it forgets the coins inside the trader block at the time, being "remembered" after introducing new coins

**Comment by Lightman314** [comment]
> I second this, happened on a 1.20.1 server, version of the mod being 2.2.0.0g Forge, prices get whipped no matter if its selling or buying, and it forgets the coins inside the trader block at the time, being "remembered" after introducing new coins or changing prices

So, from what I'm getting from this is that the data is still all there server-side (the data being the traders stored money & trade prices), but doesn't appear client-side until something happens that forces the server to send an updated version of the data on the client? This is an... interesting problem, but this does give me an idea as to what might be causing it (the probable cause being that the traders sending their data to the clients before the MasterCoinList is sent to the client, and thus the client doesn't know what to do with any coin-related data as at that point in time there are no registered coin chains, etc.)

**Comment by Lightman314** [comment]
Tested it on my test server with v2.2.0.1a, and still could not replicate the issue. That said, as an experiment I'm making v2.2.0.1b which will add a higher priority on sending the coin data packet to the client so that they should arrive and be handled before the trader data is, as it's perfectly possible that their order of operations without this is completely random based on what order forge loads the classes.

If you can please test v2.2.0.1b and let me know if this fixes the problem or not!

*Note: At this time, curseforge is having file upload issues, so you may have to download v2.2.0.1b from modrinth if you are not already doing so.*

**Comment by gaboemi** [comment]
Alright tested it on a modded server, works perfectly now, thanks :>
