### ISSUE TITLE
BUG: Server spammed with "You can no longer afford this trade" messages

### ISSUE THREAD

**Issue by AnyankaT** [Lightman314/LightmansCurrency#176]
### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Lightman's Currency Version

1.20.1-2.1.2.4b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Not sure?

### Describe the bug

For about four hours, while very few people were on the server (and not the same players the whole time), the server was spammed with literally hundreds of thousands of lines of "[Server thread/INFO] [io.github.lightman314.lightmanscurrency.LightmansCurrency/]: You can no longer afford this trade."

I don't believe it was a player, and I have no idea which trader this was. I had to restart the server to make it stop.

### To Reproduce

I don't know how to reproduce, 

### Screenshots/Logs/Crash Reports

log file was 113 mb - Dropbox link included. https://www.dropbox.com/scl/fi/imyjrbmyh4iezqsgnv1w3/latest.log?rlkey=2xnmb8xdfx24buk2n66g01k5v&dl=0

**Comment by Lightman314** [comment]
My assumption is that some player on the server has a TraderInterface box attempting to interact with a trade automatically yet cannot afford to pay the price for said trade.

That said, the debug messages were meant to be there for debug purposes not log spam, so I'll move them to the debug level log instead of info level. For the time being, you can change the `common.debugLevel` config option from the common config to 1 to hide all "Info" logger messages from my mod to prevent the log spam until I can get this fixed (or until you're willing to update to the latest LC version, as 2.1.2.4 is not the latest version at this point.

**Comment by AnyankaT** [comment]
Thanks. We're upgrading all our mods on Friday.
