### ISSUE TITLE
BUG: Input Field for InputType: TEXT is out of place

### ISSUE THREAD

**Issue by AylanJ123** [Lightman314/LightmansCurrency#185]
### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Lightman's Currency Version

2.2.0.1b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

The input field for putting values to Deposit or Withdraw from a bank account (That appears only when InputType = TEXT) looks out of place, too offsetted to the right nearly completly outside.

### To Reproduce

- Change the Master Coin List "main" chain's field InputType back to "TEXT".
- Run /reload and then /lcreload.
- Players will say the bar is "wonky", "off", "offsetted", "moved", etc.

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrency/assets/67521086/1cca8dfb-7497-436c-9870-b6a33438aa2d)
![image](https://github.com/Lightman314/LightmansCurrency/assets/67521086/0c37ec8d-c907-43a2-afda-1d375ef23c1f)

**Comment by Lightman314** [comment]
This is happening because your prefix is too long as you are using a missing translation key for your prefix. Please configure the display prefix to be a reasonable length and the issue will be resolved.

I will change this so that it notifies you of this configuration error in the future however, instead of rendering the edit box was off to the side.

**Comment by Lightman314** [comment]
Proper error notification added in v2.2.0.1f
![image](https://github.com/Lightman314/LightmansCurrency/assets/4554273/b6a2760c-7acd-45cf-b9a1-5a937dc11a31)
