### ISSUE TITLE
BUG: Immense lag when player purchases an item from card displays

### ISSUE THREAD

**Issue by dylanjkl** [Lightman314/LightmansCurrency#195]
### Minecraft Version

1.20.1

### Forge Version

NeoForge 47.1.99

### Lightman's Currency Version

lightmanscurrency-1.20.1-2.2.0.2

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Vinery (letsdo-vinery-forge-1.4.6.jar)

### Describe the bug

Whenever an item is purchased in bulk (user is sat there buying multiple items) there seems to be a huge ping spike and the servers TPS tanks.

The item I used as a test was a wine bottle from Vinery (unsure if relevant as it can happen with other items to)

The card display is linked to user bank account - my bank account currently has 16258n7d4e1g5i7c.

### To Reproduce

1. Place a card display
2. Place an item in the card display (and fill storage to max)
3. Buy many items

### Screenshots/Logs/Crash Reports

N/A (no crashes, just TPS issues)
debug file is to large to upload (35MB)

**Comment by Lightman314** [comment]
This is an issue I've been trying to figure out for quite a long time actually. I don't know why, but my new system is significantly laggier than it really should be, especially since how the math is done for coin value calculations didn't really change much...

Unfortunately I don't see this issue getting resolved any time soon, but I'll be slowly trying to improve the new system to lessen the calculation times in the future...

**Comment by Lightman314** [comment]
Should be fixed in v2.2.1.0. Feel free to re-open the ticket if this is still an issue.
