### ISSUE TITLE
crash when attempting to place regular coins in the wallet slot in the wallet hud

### ISSUE THREAD

**Issue by NyanMC** [Lightman314/LightmansCurrency#21]
this is a stupid thing to do but i managed to do it

steps to reproduce:
get a few copper coins
open the wallet gui
attempt to put the coins in the wallet slot while it's empty

crash log: [https://pastebin.com/240j5R1J](https://pastebin.com/240j5R1J)

**Comment by Lightman314** [comment]
What version of Lightman's Currency were you using, cause I supposedly fixed this issue a while ago... It shouldn't be possible to put anything that's not a wallet in the wallet slot on any version 1.0.1.6 or newer.

**Comment by Lightman314** [comment]
That said, it also shouldn't be possible to only have 22 slots in the wallet screen (minimum should by 37, 36 player inventory slots + the wallet slot), so my guess is the screen tick and the click processing happened in parallel and the slots were refreshed while the click processing was in the middle of a for loop checking the menu slots...

Friggin, this is why I hate 1.18, in 1.16 I don't have these stupid parallel processing problems, cause in 1.16 it actually uses the actual list size in the for loop instead of storing the list size to a variable and then running the for loop on that causing problems if I edit the list of slots whenever I'm unlucky enough to have it processing them in that blasted function...

**Comment by Lightman314** [comment]
Since you have not responded informing me of which Lightman's Currency version you're using, and I am unable to replicate the issue, I going to assume this is the same or a similar issue to issue #13 that I've already since corrected.
In v1.0.2.3, for 1.18 I also added some additional internal changes to the wallet screen that should prevent any and all issues with slot counts mis-matching as well, which should permanently fix or at least significantly decrease the chances of encountering a crash such as this ever again.
