### ISSUE TITLE
BUG: It appears to penetrate the model, resulting in very low fps.

### ISSUE THREAD

**Issue by QianMuu** [Lightman314/LightmansCurrency#218]
### Minecraft Version

1.19.2

### Forge Version

43.3.13 

### Lightman's Currency Version

lightmanscurrency-1.19.2-2.2.1.0b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Stabx_Modern_Guns_v8.4_mc1.19.2

### Describe the bug

The gun mod will cause the vending machine to penetrate the model and when I get close to it, my fps will become very low!

![{3CF4D59B-5F8B-41c8-911E-B39ECB1EF530}](https://github.com/Lightman314/LightmansCurrency/assets/50398180/2e113e16-a21e-4f53-9195-aa4ccf7d9ca2)

### To Reproduce

Just set up to sell firearms

### Screenshots/Logs/Crash Reports

No bugs reported. it's just a small problem

**Comment by Lightman314** [comment]
Unfortunately I have little to no control over the size of the items rendered in the vending machines, aside from scaling every items size a fixed amount, so any items who's "fixed" model (the model scaling/rotation used for item frames) is larger than the vanilla block will stick out and there's nothing I can do about it. All I can suggest is reporting this issue to the developer of the mod, as even without the direct conflict here, since I'm using a scaled down version of the item frame model it will definitely stick out when placed in an item frame as well.

As for any FPS issues you're having for rendering a lot of complicated models, please refer to the FAQ section about this exact issue, which can be found [here](https://github.com/Lightman314/LightmansCurrency/wiki/Frequently-Asked-Questions#my-game-is-lagging-when-im-around-a-lot-of-traders-how-can-i-fix-this)!
