### ISSUE TITLE
server trader not working

### ISSUE THREAD

**Issue by ZEROX7** [Lightman314/LightmansCurrency#22]
in the newest version with lc tech installed none of the trading servers are interectable on there own did you change the behavor?
tested in sp

**Comment by Lightman314** [comment]
Please follow the bug report format. I can tell you started off with the template, but I cannot help you without the exact Lightman's Currency & LC Tech versions, as compatibility between the two changes unfortunately frequently due to how many major changes I'm implementing atm (should be mostly stable for the time being, now that most of the major changes are done though).
Please explain in what way they are not working. Do existing ones fail to work, or is it only newly placed universal traders. Only universal fluid traders, or all universal traders (item & fluid). I need to know these details my man...

**Comment by ZEROX7** [comment]
forge version 39.0.20, lightmans currency 1.0.2.3, discord intigration version 0.0.1.3 lc tech version 0.0.1.0 newly created world on both sp and mp and all server traders dont work fluid and item it seems like the trading machine is working so for me it seems like the server wide trading system failed maybe?

**Comment by ZEROX7** [comment]
maybe due to the team intigration?

**Comment by ZEROX7** [comment]
and if you want to my modpack is on curseforge hehe singularity create :P

**Comment by Lightman314** [comment]
I'll look into it, but if it's not working for the universal item traders, it probably has something to do with how I tweaked how the universal traders are registered to the Trading Office. I'll look into it and have it fixed asap.

**Comment by Lightman314** [comment]
Found the problem, I'll upload a patch shortly. Fortunately, I think it should have still saved them properly, so reloading the world will result in the ones that you have placed functioning properly, it just didn't assign the trader ID to the trader itself, so it had problems syncing the trader data with the client, which is why you couldn't open the UI.

**Comment by Lightman314** [comment]
Fixed in version 1.0.2.4.
