### ISSUE TITLE
BUG: Lightman's Currency prevents Ancient Saplings from Nature's Aura from growing

### ISSUE THREAD

**Issue by hjoyn** [Lightman314/LightmansCurrency#235]
### Minecraft Version

1.20.1

### Forge Version

47.3.0

### Lightman's Currency Version

2.2.2.3

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Nature's Aura 39.4

### Describe the bug

Ancient saplings cannot grow. When they attempt to, via growth ticks or bonemeal, it fails and throws an error. A quick look at the log file indicates this occurs at the code added in https://github.com/Lightman314/LightmansCurrency/issues/226, as this issue does not occur in 2.2.1.3b. However, I'm not sure if this is an issue in lightman's currency, nature's aura, or an interaction of both. 

### To Reproduce

1. Place an Ancient Sapling.
2. Wait for it to grow or use bonemeal to force it to grow.

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/user-attachments/files/16151932/latest.log)

**Comment by Lightman314** [comment]
The only time that my mod should block anything from growing is if the feature it's growing extends the `AbstractHugeMushroomFeature` class (i.e. is a huge mushroom-type feature) and there is an LC block within a 7x12x7 area around the sapling/mushroom (with the sapling at the center, such that the LC block will only block if 3 or fewer blocks away).

Therefore if anything is causing this issue it's the fact that their tree for some odd reason extends a Huge Mushroom feature class instead of a tree feature or something else along those lines, and regardless this issue can be easily avoided by simply not growing these types of trees near any blocks added by my mod.

**Comment by hjoyn** [comment]
The growth is being blocked regardless of the presence of any blocks from your mod. It seems there is just a null pointer exception in the mushroom blocking code.

**Comment by Lightman314** [comment]
So there is, thanks for pointing that out as that completely slipped my notice.
I'll make sure to have that fixed in the next build.

**Comment by Lightman314** [comment]
Sorry for the late reply, but this has been fixed for 1.20.1 since v2.2.2.4
