### ISSUE TITLE
BUG: Coins aren't added to loottables properly in 1.19.2

### ISSUE THREAD

**Issue by DungeonMasterOof** [Lightman314/LightmansCurrency#238]
### Minecraft Version

1.19.2

### Forge Version

43.2.21

### Lightman's Currency Version

2.2.1.3c

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

It also happens with vanilla loottables, but if needed:
rotten creatures 1.0.1
better animals plus 11.0.10

### Describe the bug

Coins aren't added to every loottable after the first one in the list. That behaviour is seen in basic T2 loot -- boss T6 for entities, T1 -- T6 for chests.

### To Reproduce

Please watch the videos below.
1) https://youtu.be/U3bp7YTmO38
2) https://youtu.be/NvubZIBnchk

### Screenshots/Logs/Crash Reports

[2024-07-14-5.log.gz](https://github.com/user-attachments/files/16228853/2024-07-14-5.log.gz)
Full undecoded file

[2024-07-14-5.log](https://github.com/user-attachments/files/16228863/2024-07-14-5.log)
[latest.log](https://github.com/user-attachments/files/16228860/latest.log)

All that I have for that game session

**Comment by DungeonMasterOof** [comment]
For anyone interested: I've tried to somehow overcome that problem.
It may be caused by using single objects in code instead of lists in the simplest case, but I don't really know.
I created a tag for entities using CraftTweaker mod, and that worked well. So, actually, you may create tags for every needed tier and put them in config, this will work for entities. You may look at screenshots. I haven't found any way to deal with this bug for chests loottables, so I've decided to search stable version.
!!! I noticed that problem exists since 2.1.2.4 backport for 1.19.2 version. The only version that works for me is pretty old 2.1.0.0g
Any further versions are problematic.
![изображение](https://github.com/u
![123](https://github.com/user-attachments/assets/14611791-a574-4b31-8c8e-bf20f070394b)
ser-attachments/assets/842a51d0-415b-48a0-b028-cfab159a1352)

**Comment by Lightman314** [comment]
Finally got around to testing it, and was unable to replicate after adding a random mob to the 2nd option of the T5 list, reloading the config, and then spawning one with the summon command and watching it drop coins once I stab it with my sharpness 100 sword (because if I'm gonna kill it, I might as well let it die quickly 😛) 

I should also note that from this screenshot from your video, the config inputs have an unnecessary space within the quotations as underlined here:
![image](https://github.com/user-attachments/assets/c5304c9a-4927-4bde-a40e-8abb272a98c1)

I should note that the mod won't clear any empty space from the config inputs, as whenever I mob dies I get it's ID ("minecraft:skeleton" for example) and do a direct string comparison from the list.

And naturally `"minecraft:skeleton_horse"` does NOT equal `" minecraft:skeleton_horse"`.

So at this point all I can assume is that this is user-error on your part for leaving that empty space within the config inputs.
For future reference, please also attach the config file in question for issues directly related to a config option not working so I can more easily catch minor syntax errors and resolve the issue immediately, instead of making me watch several minutes of youtube videos that I'll thusly have scrutinize and pause to find the data I actually need (though the videos are definitely a helpful addition, I'm mostly just requesting that you be a bit more thorough with attaching **all** relevant data)
