### ISSUE TITLE
BUG: JEI recipes not appearing

### ISSUE THREAD

**Issue by LunarN0v4** [Lightman314/LightmansCurrency#254]
### Minecraft Version

1.21

### Forge Version

Fabric 0.16.5

### Lightman's Currency Version

1.0.2.4

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

JEI recipes do not display

### To Reproduce

1. Install JEI + Lightman's Currency + other mods (in logs) if bug isn't reproduced
2. View JEI recipes for items such as coins with custom methods of obtaining/usage
3. Recipes for creating the items and/or recipes for usage of the items are missing are missing

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/user-attachments/files/17323956/latest.log)

**Comment by Lightman314** [comment]
Ah, I see this issue here. You're using LC Fabric, not main LC (forge/neoforge). They have completely different code bases due to how different fabric is from forge, so all issues/feature requests for LC Fabric need to be posted here:
https://github.com/Lightman314/LightmansCurrencyFabric/issues

Having said that, LC Fabric is no longer supported and will not be receiving any feature updates at this time. That said LC Fabric does have an REI plugin that does exactly what you're asking for, as when I first started making LC Fabric there was no Fabric version of JEI.
