### ISSUE TITLE
[ QUESTION ] BlockEntityBlockHelper.class

### ISSUE THREAD

**Issue by Xelbayria** [Lightman314/LightmansCurrency#264]
### Minecraft Version

1.18.2

### Forge/NeoForge Version

40.2.10

### Lightman's Currency Version

2.1.2.5d

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Every Compat

### Describe the bug

Hello again, 

I see there are no option to create a QUESTION issue. This is clearly a question to ask about BlockEntityBlockHelper. Does it add the generated Block from EveryCompat to Renderer's registry? 

for some reason, it's not rendering the item but It registered the block with BlockEntity class. 

I cannot find the cause of why item is not being rendered. 1.18.2's code is quite old and it doesn't have the same code as 1.19.2 or 1.20.1 where I can simply use `.addTile()` to include the generated block in Renderer's registry and also BlockEntity's registry 

### To Reproduce

N\A

### Screenshots/Logs/Crash Reports (FILES ONLY)

N\A

**Comment by MagikHorse** [comment]
The reason why there's no "question" tag is because this is a bug reporting page, not a question asking page. The front page of the project already says to go to the wiki for common questions or the Discord for other developmental questions like this one.

I know he's usually pretty quick to answer on Discord when he's not at his day job, so you will likely have a better experience there.

**Comment by Xelbayria** [comment]
that's a fair point. I'll go on discord and discuss with him about the 1.18.2
