### ISSUE TITLE
BUG: ISSUE_DESCRIPTION

### ISSUE THREAD

**Issue by s4sutler100** [Lightman314/LightmansCurrency#266]
### Minecraft Version

1.21/1.21.1

### Forge/NeoForge Version

1.21.1.180

### Lightman's Currency Version

1.21.1+14

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

resource packs  dont match what the server sees  resource pack  for newer version of neoforge    need the ones  for 1.21.80

### To Reproduce

not sure

### Screenshots/Logs/Crash Reports (FILES ONLY)

[latest.log](https://github.com/user-attachments/files/17840111/latest.log)
this is what I see
![2024-11-20_21 11 59](https://github.com/user-attachments/assets/f1dd9b29-e1d4-489d-bcf0-37e46a1b9853)
![2024-11-20_21 12 40](https://github.com/user-attachments/assets/df712e64-0c51-490a-bfb6-b9188a16fb77)
![2024-11-20_21 13 12](https://github.com/user-attachments/assets/d647b995-b2e1-4a35-a736-a483382dc299)   

This is what the server owner sees
![image](https://github.com/user-attachments/assets/02c0261b-896b-4d3d-9d3f-34784126f68e)
![image](https://github.com/user-attachments/assets/b611277d-5d83-4355-b745-a7545babf02f)

**Comment by Lightman314** [comment]
There was an issue with the data generation when I uploaded v2.2.4.0b. Please re-download for a fresh copy with all of the proper model files included.

Also, **very important**. 1.21.1+14 is **NOT** a valid Lightman's Currency version. Please make sure to provide accurate information on what version you are using when reporting issues. I was able to figure it out this time because I already knew about this issue beforehand, but in the future this is **very important** information that must be provided correctly.
