### ISSUE TITLE
BUG: Command exception: /lcadmin taxes openServerTax

### ISSUE THREAD

**Issue by Normslabs** [Lightman314/LightmansCurrency#273]
### Minecraft Version

1.20.1

### Forge/NeoForge Version

47.3.4

### Lightman's Currency Version

2.2.4.1

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

LC Tech 0.2.1.13

### Describe the bug

Single player world. Admin mode toggled on (also tried with off).
/lcadmin taxes openServerTax throws an exception. Displayed in chat: "An unexpected error occured trying to execute that command".
Image showing the chat message as well as the exception stack trace provided. I also started the MC instance and just reproduced the bug before quitting to upload a run log that is as small as possible (still, its big, our modpack has ~240 mods).

![image](https://github.com/user-attachments/assets/feb09dc7-ce1e-4a38-b5eb-ff18d79e7608)
[lc_currency_exception.txt](https://github.com/user-attachments/files/18087497/lc_currency_exception.txt)

### To Reproduce

Open chat; enter the command. => error thrown.
Toggle yourself as admin, open chat, enter command -> error thrown.
Set up a tax collector, open chat, enter command -> error thrown.

### Screenshots/Logs/Crash Reports (FILES ONLY)

Error situation begins at line 5317 in the logs

[latest.log](https://github.com/user-attachments/files/18087559/latest.log)

**Comment by Normslabs** [comment]
Did a second test on a MC instance with only LC, LC Tech, and DuckMoney 1.0.0 (i'm using their items as coins) as mods.
Same problem occured.

Here's the run log:
[latest.log](https://github.com/user-attachments/files/18087709/latest.log)

**Comment by Lightman314** [comment]
I somehow manages to mess up the TaxEntry constructor with a null Player input on 1.20.1 (1.21 has the correction functionality here fortunately), which was resulting in a null pointer exception when attempting to sync the tax collector to the connected clients, and said exception was being safely caught by the command execution instead of crashing the entire server like it normally would have otherwise.

Either way, this is now fixed in 1.20.1-2.2.4.1b. Thank you for reporting :)
