### ISSUE TITLE
Client crashes and removes inventory when trying to access small item trade server settings

### ISSUE THREAD

**Issue by cgguardian** [Lightman314/LightmansCurrency#28]
The best part of this is that it decided to not generate a crash log.

Upon relogging after the crash, my inventory was inside of another nearby (extra large) trade server.

**Comment by Lightman314** [comment]
I require more context. In the future please follow the bug report template when reporting issues such as these so that I know where to start looking. Please provide the following:

- Minecraft Version
- Forge Version
- Lightman's Currency Version

In this particular case, I'd also like to know a bit more context about the situation. Were you playing in a single-player world, or were you connected to a server? Did the server also crash when you crashed, or did it keep on running just fine?

In addition, even if a crash log wasn't created, there should still be a log file in the "logs" folder of your Minecraft installation which will likely contain useful information. If you haven't re-launched the game since the game crashed, the latest.log file should be perfectly fine, but if you have you'll likely need to figure out which of the dated "YYYY-MM-DD-X.log.gz" files contains the relevant log (you can open the .gz file with any zip editor, and then just scroll to the very bottom of the log file within and find the one that either ends in a crash, or just abruptly ends with no explaination (doesn't end with "[DATE TIME] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!)).

**Comment by Lightman314** [comment]
Given a lack of response with the needed info, and no other reports of the same I'm closing the issue. Feel free to re-open if you wish to give the info I have requested.
