### ISSUE TITLE
[Feature Request] Ideas I had while playing

### ISSUE THREAD

**Issue by faelBrunnoS** [Lightman314/LightmansCurrency#34]
### Bank Account and ATM

- [ ] The bank account could have a function to transfer and receive coins from other players.
- [x] If the above function were implemented, the portable ATM would only work to manage the bank account and also transfer and receive coins from other players.
Because in my opinion, leaving it as it is, makes the old ATM useless, as it is more practical to use one that you can carry wherever you want and that you can use without putting it on the floor.
**_I think that would bring more useful and interesting mechanics to the two items and also the bank account function._**
~~- [ ] If the transfer function to other players was implemented, the team's bank account could have a function to send values to all members, for example:
_In a slot I put 1 netherite coin, then I choose if only members or if admin will also receive it.
After that I hit the transfer button and it will convert that 1 netherite coin to the amount of players, if it was 5 players it would divide 1 coin by 5, using the default values would be 2 diamond coins for every 1._
 _**(An interesting feature for servers with clans that share profits with their members)**_~~

~~### Coinpiles and Coin Blocks Recipe~~
~~- [ ] The recipe for coinpiles and coin blocks could be shapeless and the limit in the configuration file could be greater than 9.
16 for example would be good!
_Example: 1 coin block is equivalent to 16 coins and 1 coinpile is equivalent to a stack of coins ( 4 coin blocks )._
_I know I can make datapacks for this but not everyone knows_~~

### Team Manager
- [ ] Team management could also be triggered by some item (A computer for example).
I wouldn't mind if it was the same model and texture as the cash register, I just wish it had a small screen in my office.
_(The fewer commands the better haha)_

**Comment by Lightman314** [comment]
The bank account suggestions do seem like good ideas, and when I get some time I'll probably go ahead and see if I can add them (hopefully there'll be screen space on the ATM screen, otherwise I might need to make another tab for transfers). The team transfer to all members/players could possibly be added to the Bank Account management screen in the Team Management menu, although it'll probably behave more along the lines of "transfer 5 copper to all members/admins" instead of a "divide 5 copper between all members/admins".

As for the Coinpile & Coin Block Recipe/config suggestions, I'm not 100% certain what you're asking for here, but I have no plans on ever editing the coin pile/block recipes included with the mod, and as you've said a datapack & something like craft tweaker (to remove the original recipes) can easily modify the recipes if someone wants to modify the recipes for their modpack. I also don't see the point of changing the config limit as no matter what the recipe is, you can only ever fit 9 coins into the crafting grid so making a coin pile worth 14 coins in the config would literally generate at least 5 coins of "value" out of nowhere.

As for the Team Manager, I could probably add an item to trigger it, but there's no real need as it has it's own personal key bind (']' by default) that opens the screen from anywhere without the need for an item.

**Comment by faelBrunnoS** [comment]
Glad you're thinking of the idea!
I really like your mod, it was the first Currency mod I installed!
The others are good, but yours is unbeatable!
Congratulations!

I'll keep sharing my ideas here, I'm also a translator and I'm already finishing a translation into my native language (PT-BR)
I'll make a pull request soon!

I'm also studying design, I'll make some textures for your mod and send them to you, maybe you'll like some!

**Comment by Lightman314** [comment]
Suggestion 1 (Bank Account Coin Transfer/Gifting):
As of v1.0.5.2, there's is now a method of transferring coins from one bank account to another player/teams bank account. The receiving it done automatically, and logged in the new bank account logger so they will be able to confirm that the payment was received if it was something they were expecting.

Suggestion 2 (Removing certain features from the portable ATM):
I still have no plans on making the portable ATM any different from the block version of it, especially since they use the same resources to craft. The block version still has it's use as a way to save storage space when placed conveniently in public spaces such as a server-managed shopping district, etc, so I don't feel the portable version having the same features away, as the added convenience it balanced out by the fact that it takes up an inventory/hotbar slot to use.

Suggestion 3 (Coin Pile/Coin Block value limit changes):
While this wasn't completely intentional, the new method of registering coins added in v1.0.5.0 does now make it such that you can define the relative coin values of coin piles/coin blocks to any value you wish, so people who use craft-tweaker to modify the coin pile/block recipes to require more than the vanilla 9 items that can fit in a crafting table can now define the relative values to match.

Suggestion 4 (Item to open the Team Manager screen):
I am going to stand by what I stated earlier, and I'm not going to bother making an item to trigger opening the Team Management screen. As I stated before there's really no need since there's a key bind allowing you to open the team management screen without the need to craft any items, or run the /lcteammanager command, etc. In fact, adding a craftable item could cause confusion to players that think they need the item in order to open the team management screen, causing them to waste resources crafting the team management terminal instead of using those resources on something more important.

And now that I've addressed and/or implemented all of the suggestions, I'm going to close the ticket.
