### ISSUE TITLE
BUG: very low fps

### ISSUE THREAD

**Issue by PabloMk2** [Lightman314/LightmansCurrency#51]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.0.19
Lightman's Currency Version (REQUIRED): 1.1.1.1a
Other Relevant Mods & Version (LC Tech, etc.): none
Connection Type (Single-player, server/client, LAN world): server

**Describe the bug**
Very low fps 

Vending machines drops fps up to 10-15 when they are within drawable chunks, when they are behind the fps stabilizes at around 70-100. The problem manifests itself with BSL shaders and many others. Disabling item rendering in the config does not fix the situation. It cannot depend on the power of the computer, because I have Xeon e5 2678 v3 and rtx 2080ti, also it does not depend on other mods. This mod is magnificent and I want to find a solution to the problem:(

Thanks in advance for your reply

**Comment by Lightman314** [comment]
My apologies, but the vending machines have a relatively large polygon count compared to other minecraft blocks (due to the shelves and poles that the items get displayed on), so any shader that adds shadows will likely generate a fair amount of lag due to the large amount of parts that it needs to calculate shadows for. Unfortunately there is little I can do, as I'm using vanilla block modeling for the vending machines, so any framerate issues are caused purely by the shaders, and I am not willing to change the vending machine models of something like this, especially since there are no noticeable frame rate issues when running with vanilla rendering.
