### ISSUE TITLE
[1.18.2] Feature Request: Curio support for wallets

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#57]
**Is your feature request related to a problem? Please describe.**
Sort of. The coin bag slot feels out of place in the inventory.

**Describe the solution you'd like**
It's in the title - add support for Curio (preferably as a custom slot), and then remove the base slot if Curio is installed.

**Describe alternatives you've considered**
A config option to move the wallet slot position, but I'd prefer Curio support.

**Additional context**
None, but it would also be nice if you made all the mod configs go into the `lightmanscurrency` folder.

**Comment by Lightman314** [comment]
While I was unwilling to re-implement curio support, due to some issues I encountered in my several re-works of the wallet slot, I feel that the wallet slot is workable enough now that I have the flexibility to re-add it as a curios slot.

That said, in the mean time, the client config very much *does* have a config option to move the wallet slot's position in the players inventory.

**Comment by Lightman314** [comment]
Curios support has now officially been added as of v1.1.5.4.
