### ISSUE TITLE
Feature Request: Assign a currency name to coins, as well as having said currency display on their tooltips & in UIs

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#58]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to give my currency a custom name, and although I could do that for tooltips & item names, it would be nice if the mod config did it.

**Describe the solution you'd like**
Adding a config file to name the currency, and having that currency name display in UIs (e.g. the ATM would say "100 CraftCoins" instead of "1e1g3i")

**Describe alternatives you've considered**
Renaming them myself, but that doesn't solve the UI issue.

**Additional context**

**Comment by Lightman314** [comment]
There in the "coin_value_display" section of the server config (found in "_world_/serverconfig/lightmanscurrency-server.toml"), there are several options to change from the "DEFAULT" display mode (1n5g) to a "VALUE" based display mode which basically defines a configurable coin as **$1**  (defaults to the gold coin, thus making the copper coins the equivalent of a penny or **$0.01**). Combine that with the valueFormat option, and you can make all instances where a coin value is displayed (wallet tooltips, trader screens, bank account balance, etc.) display as your desired currency "unit", (and since it's a string input, you could do something as simple as making it appear as USD with "${value}", or, to get the results in your request/example, format it as "{value} CraftCoins", and then use the coin renamed to CraftCoin in your resource pack's language as the "baseValueCoin" coin id.

**Comment by vizthex123** [comment]
I did notice that, yeah. Still not use to this new server config system, so I didn't think to check there until a few minutes ago. Was coming back to say so & close the issue. Nice how it's there.

**Comment by AnyankaT** [comment]
Has this feature been removed from the current version? We updated, and now our °1234 values are gone, replaced with 1e2g3i4c.

**Comment by Lightman314** [comment]
Due to multiple coin chains now being possible, this option has been moved from the server config into the MasterCoinList config so that the display and input type can be defined for each coin chain independently.of each other.

Details can be found in the wiki [here](https://github.com/Lightman314/LightmansCurrency/wiki/Master-Coin-List-Config#display-types).

**Comment by AnyankaT** [comment]
I'm sorry, I've read the wiki now, but I don't understand how to change the config file to add the proper display format for the main coin chain. I tried, and it didn't work.
[MasterCoinList.json](https://github.com/Lightman314/LightmansCurrency/files/14075007/MasterCoinList.json)

**Comment by Lightman314** [comment]
I'm a bit confused as to why your MasterCoinList contains the `chocolate_coin` entries as these are hard-coded and never written to file. Either way, that has nothing to do with your issue

Aside from that, the issue seems to be that you're defining the `displayFormat` and `displayFormatWordy` values as translatable text that does not exist. You need to replace these with a valid [Json Text](https://minecraft.fandom.com/wiki/Raw_JSON_text_format), but if you'd like a basic example of a simple string text (similar to how the old config had it set), the following would work just fine:
`"displayFormat":"${value}"`

**Comment by AnyankaT** [comment]
The chocolate coin entries were in the file generated by the mod. I don't
lnow what to tell you ...

Michelle Smith
Independent Language Trainer
