### ISSUE TITLE
Feature Request: Mass-buy/sell keyboard shortcuts

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#60]
**Is your feature request related to a problem? Please describe.**
Yes, having to spam click is annoying.

**Describe the solution you'd like**
It would be great if we could shift+click for a stack of items, and control+click for 16 items, and alt+click for 32 items (in every shop UI)

**Describe alternatives you've considered**
None

**Additional context**
Having them be regular game keybinds could help some peoplel, but shift & control are good by default.

**Comment by Lightman314** [comment]
I have no plans on ever adding key binds to multiply the number of times a trade is interacted with per click, as multiplying a trade that sells 2 stacks of an item by 64 would result in a royal butt-ton of items all over the floor as the don't have enough inventory space for 128 stacks of items. If you wish to buy items a stack at a time, convince the person selling them to sell them by the stack instead of individually.
