### ISSUE TITLE
Feature Request: Move the value input box on the ATM's UI below where it says "balance"

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#63]
**Is your feature request related to a problem? Please describe.**
Yes, as I posted in #59 the UI doesn't fully fit on-screen, and I just realized that you could move the text input box and fix this issue.

**Describe the solution you'd like**
Just move the input box below where it says "balance", that way it will fit when using auto UI size; as well as looking nicer overall.

The box might need to be slightly smaller to fit, but this would be a great addition overall imo.

**Describe alternatives you've considered**
None

**Additional context**
Screenshots demonstrating what I mean, as sort of a "proof of concept":
![image](https://user-images.githubusercontent.com/31721920/175798228-59654842-a59b-452a-a404-980fd11eb9c0.png)

My edit:
![example](https://user-images.githubusercontent.com/31721920/175798858-db5bddce-acfe-4d1d-9468-3f265c208a4d.png)

I think it looks a lot better this way, and eliminates the huge amount of empty space that was in the center.

Of course, I'm no UI designer, so it can re-aligned - but I do think the box being in the middle is way more readable overall.

**Comment by vizthex123** [comment]
The same thing could be done on the transfer UI too, the player name box could be moved up a bit, and the amount box could go below it.

**Comment by Lightman314** [comment]
The problem with this is that it wouldn't fit with the full-sized "default" coin value input method (believe me, I tried when I re-worked it to have a fixed width regardless of how many coins are registered). That said, I will probably go ahead and re-size the entire ATM UI so that it will have enough vertical space to fit everything, and making the entire menu taller will make it properly centered vertically such that it should all fix in a 256 pixel tall area, and thus fit the auto GUI scale. I had a couple ATM UI reworks planned, so I'll probably work it in then.

**Comment by vizthex123** [comment]
> The problem with this is that it wouldn't fit with the full-sized "default" coin value input method (believe me, I tried when I re-worked it to have a fixed width regardless of how many coins are registered). That said, I will probably go ahead and re-size the entire ATM UI so that it will have enough vertical space to fit everything, and making the entire menu taller will make it properly centered vertically such that it should all fix in a 256 pixel tall area, and thus fit the auto GUI scale. I had a couple ATM UI reworks planned, so I'll probably work it in then.

yeah, that'd be noice. I would love to have this centered bar design (I didn't resize the text box input when I made that mock-up image), but idk if it's possible.

**Comment by Lightman314** [comment]
I managed to resize it to 243 "pixels" tall, and get everything to fit.
The transfer tab now looks like this:
![image](https://user-images.githubusercontent.com/4554273/175831652-45bc5f85-a081-4dcf-9ed5-9c3e28ca50e5.png)

And the interaction tab now looks like this:
![image](https://user-images.githubusercontent.com/4554273/175831691-805baec8-1d8b-43d7-a538-ac59d3384d54.png)

Conveniently enough, I found a few small bugs with how the transfer response messages giving inaccurate transfer amounts if the sending bank account doesn't have the requested transfer amount, so those will get fixed in the process as well, but there's a few other changes I'm going to make while I'm working on the ATM screen, so it will likely still be a few days until this change is published.

**Comment by vizthex123** [comment]
ay, nice. Thanks a ton for doing this.

I need it on the 1.18.2 version if ya could though, but yeah it looks neat.

**Comment by Lightman314** [comment]
This should end up on both the 1.18.2 and the 1.19 versions.

**Comment by vizthex123** [comment]
noice

**Comment by vizthex123** [comment]
I also found that the coin input box is covered up by the item selection one inside of shop blocks, bit of an annoying bug. Applies to purchases & sales.

![image](https://user-images.githubusercontent.com/31721920/175836001-6e123025-cdcf-40fa-9bc1-d1b9290c5868.png)

**Comment by Lightman314** [comment]
That's odd, as the value input shouldn't even be rendering if the item edit widget is visible, and vice-versa. There's probably an issue with it not making it's "child" widgets match it's visibility when in value mode (as opposed to the default mode which hides it just fine. I'll make sure it's fixed before the next update.

**Comment by vizthex123** [comment]
so it'll be fixed when the UI change comes out? noice.

**Comment by vizthex123** [comment]
also, it'd be nice if you could fix the wallet UIs in the same way it'd be nice. Maybe remove the big empty space between the text box and buttons?
![image](https://user-images.githubusercontent.com/31721920/175850896-16cfb21d-0f9a-44c6-a02a-9e67018b2c60.png)

**Comment by Lightman314** [comment]
I've said this a dozen times now, but I still don't think you realize this. The Coin Value Input is sized vertically to match the largest possible size it can be, (so that we don't have things overlapping when using the "standard" input method/config option). These "remove the empty space", and "it'll fit here" comments do not apply to the standard coin value input method, and thus the changes you suggest while giving screenshots of the far simpler/smaller mode cannot be applied unless there's a significant amount of empty space (which there isn't, otherwise I would have simply put it into said empty space in the first place. I may not be the best at UI design, but I'm not an idiot...)

I do plan on re-working the wallet's bank account interaction UI (probably by giving the wallet menu multiple tabs similar to how the Trader Storage menu works), but that will likely be a future update. Also, this feature request is getting a fair amount off-track, and tickets really aren't the best place to make such small tweak requests. I'd recommend joining the discord (link is at the bottom of the mods curseforge page) if you'd like to have a more proper discussion of minor tweaks that can be made.

**Comment by vizthex123** [comment]
noice, thanks.

I actually didn't know there was a discord, but I'll go ahead and join it. Sorry for pestering you so much, lol.
