### ISSUE TITLE
Trouble placing machines on certain blocks 1.16.5

### ISSUE THREAD

**Issue by Sublime204** [Lightman314/LightmansCurrency#7]
Love the mod but I seem to be having difficulties placing the vending and other machines in certain places including in stores that we've built on our Forge 1.16.5 v36.2.0 server with version 0.8.4.8 of LightmansCurrency. Even after breaking a machine to move it over a block I run into problems even placing it back in the same place.

**Comment by Lightman314** [comment]
I tested placing both large and normal vending machines both in single-player and on a server-client with forge 36.2.0, and their placement and destruction is working as-intended, so I'm gonna have to request more details before I can address this issue. Are you sure it's not just a server-client desync via lag or other such shenanigans? Also what other machines are you referring to? The ATM and other such 2-tall blocks? Or are some of the single-block traders having placement issues.

p.s. keep in mind that any block that isn't air such as grass, vines, or even water at any position of the multi-blocks final position will prevent it from being placed.

**Comment by Lightman314** [comment]
If it's working in some places, and not working in others, it sounds like another mod is preventing block placement in general (that or you're trying to place too close to the vanilla spawn protection). Once again though, I need more details than "it works at one spot, but doesn't work at another". Does it block only placement of the machines, or does it block all block placement in general? Once again, I don't have enough info to even get started looking into it.

A latest.log file would be extremely helpful, or if not that a video reproducing the issue, cause then I could see if errors are happening, and if so where in the code so I know where to look. This is the first report of any issues with block placement though, and I haven't changed the code for the multi-blocks since they were first made so if there were any problems they should have been reported months ago.

If this is happening on a server that you don't own though, I would first report this issue with them so they can check for conflicting mods/configs/world corruption, etc. or if there are other mods in the modpack that are supposed to prevent block placement in a manner such as this.

**Comment by Sublime204** [comment]
Sorry for being so vague, it's a really confusing problem that's tough to troubleshoot. I did just get the below 2 records on my server not sure if it helps. It is a fresh server that's only about a week old now. In the places I'm not able to place the machines I can place other blocks and there is plenty of room to place them down so it really doesn't make much sense. I just came across your mod with the current version so I haven't tried previous versions either but I would agree you'd think others would have run into this problem as well. What log file(s) would you need to look further into it?
![Capture](https://user-images.githubusercontent.com/91436562/137156595-62f10135-e793-4ada-a985-ed0f52d32f50.JPG)
l.

**Comment by Lightman314** [comment]
Well that's certainly insightful, it looks like there's an awesomeshop TrashCanTileEntity where my ItemTraderTileEntity should be, realistically though, I only run the function that would send that error when you interact with a trader, not when it's placed?

Try putting a vanilla tile entity down (chest, furnace, anything that stores items) to reset the tile entity for that position and try again? If that doesn't work, try putting the trash can back and breaking it. If it prevents you from placing even the vanilla ones, (especially after all that), then it's clearly a problem with the awesomeshop trash can, and you should report the issue to them.

That said, the ideal logs to have to bug fixing are the crash report if the issue is a crash, otherwise either the latest.log or debug.log from the server logs would be ideal.

**Comment by Sublime204** [comment]
Funny thing is I don't even have a trash can placed anywhere near where I'm trying to place the machines not even in the building's I'm trying to place them in. I have tried to place a vanilla block where I'm trying to place the machine than tried to place a machine afterwards even deleted the blocks underneath and tried placing the machines a block below and above with no luck it's very bizarre.

I'm not getting any crashes so I'll include a copy of my latest.log and debug.log for review. 

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/7340162/latest.log)
[debug.log](https://github.com/Lightman314/LightmansCurrency/files/7340163/debug.log)

**Comment by Lightman314** [comment]
Was there a trash can at that spot in the past, cause THAT seems to be what's causing the issue. Not a currently existing trash can, but one that's been destroyed but is corrupting the block.

Also, you say you placed vanilla blocks, but did you place a vanilla TILE ENTITY (chest or furnace block speficially) in the exact spot that you're unable to place the trade machines, cause a non tile entity block wont' do anything to the ghost tile entity that's causing the problem.

If neither of these fix the problem, all I can suggest is reporting the issue to the awesomeshop mod cause it's their ghosting tile entity that's causing problems.
