### ISSUE TITLE
BUG: {GUI is not fully seen at Scale 4}

### ISSUE THREAD

**Issue by ThomasTCE** [Lightman314/LightmansCurrency#75]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.1.68
Lightman's Currency Version (REQUIRED): 1.1.6.5a
Other Relevant Mods & Version (LC Tech, etc.): not revelant besides vanilla
Connection Type (Single-player, server/client, LAN world): client

**Describe the bug**
The gui of the paygate and all terminals/shelfs/armor displays/card displays/display case/(large) vending machines/freezers/ticket kiosk/item network traders are cut off at the top of the screen at gui scale 4, the problem is that if i put on a smaller gui scale it hurts my eyes, gives me a headache, and makes me very disoriented.
Mojang changed the old gui scale 3 to 4 around 1.13 or 1.14 and because of that a lot is broken, without me being able to get use to the smaller scales.

**To Reproduce**
1. Go to options, then go to video settings
2. turn the GUI scale to 4.
3. interact with any block/item of the above
4. sit in windowed mode

Screenshot:
![Schermopname (133)](https://user-images.githubusercontent.com/109741051/180223425-4fb9eeb2-0a89-4a91-b433-721b31616165.png)

**Expected behavior**
the top buttons are half gone and you can barely/not read the text from it

**Additional context**

**Comment by Lightman314** [comment]
While I won't deny this isn't ideal, I very clearly warn you about this in my mods Curseforge page.
![image](https://user-images.githubusercontent.com/4554273/180333869-5e5e64f5-06e2-4126-b331-5a13d9e8a595.png)

Sadly, there's not a lot I can do to fix this as I can't really make the screen any smaller. Fortunately the buttons are all still reachable, so you can still access all of the features (except some admin features on Create Auction tab), etc. so while I may look into this if I get some free time I hope you'll understand that it's a low priority issue.

**Comment by ThomasTCE** [comment]
alright, i don't know if a scrolling feature would be able to be made, but that could be a way of making things smaller, while still keeping the same amount of features and choices, just an idea if that is a way to fix it.

**Comment by Lightman314** [comment]
There already is a scrolling feature, that's why I was able to revamp the trade buttons, make the menu a constant size (as larger item traders used to be too large for GUI scale 4 entirely), and increase the trade limit for creative traders. That said, I have thought of an easy fix to get the buttons to fit on the screen properly:

I can just move the buttons from the top of the UI to the side. I'll probably put them on the left/right sides of the players inventory/coin slot area, as the narrower background leaves a little extra room for the buttons to fit without overlapping with JEI, etc.

**Comment by Lightman314** [comment]
Fixed in v1.2.0.0
