### ISSUE TITLE
BUG: Failed to load correctly MC 1.19.1 Forge 42.0.1

### ISSUE THREAD

**Issue by HarryPlopper91** [Lightman314/LightmansCurrency#79]
Minecraft Version (REQUIRED):  1.19.1
Forge Version (REQUIRED): 42.0.1
Lightman's Currency Version (REQUIRED): lightmanscurrency-1.19-1.1.5.4a.jar
Other Relevant Mods & Version (LC Tech, etc.): NA
Connection Type (Single-player, server/client, LAN world): ANY

**Describe the bug**
`Lightman's Currency (lightmanscurrency) has failed to load correctly`
`java.lang.reflect.InvocationTargetException: null`

**To Reproduce**
1. Install Mod
2. Launch Game
3. Error loading mod screen, cannot continue

**Expected behavior**
Game to load correctly

**Screenshots/Logs/Crash Reports**
[PasteBin](https://pastebin.com/JYP1jbDv)

**Additional context**
Most likely due to recent changes in Forge.

**Comment by Lightman314** [comment]
First off, you're far from using the latest version, as v1.1.6.6b updated the required forge version to update to accommodate forge changes.

Second off. The 1.19 version is not flagged as being compatible with 1.19.1, so any issues with it not working on 1.19.1 due to forge or minecraft changes is completely invalid.

**Comment by HarryPlopper91** [comment]
First off, I really don't understand why people get so defensive about these things and **act like a child**.

Second maybe you as the mod dev should be asking yourself hmm why would someone be coming directly to my GitHub with an issue on something that should not be available for 1.19.1?

Third check yourself and your publishing settings my guy, your the issue here.... was just trying to help you out by posting about this smh.... as 1.19.1 didn't come out till a few days ago, and you uploaded this version last month, it was most likely a fat finger click on your end, and you simply need to go onto CurseForge to correct the issue for that version as I originally posted about and uncheck v1.19.1. As a fellow software dev and minecraft pack developer I dont have the time to go and verify publishing dates for each mod pack or API when adding them, especially when getting into the three and four hundred ranges. It falls in your area of responsibility to ensure you are uploading with the correct compatibility versions checked.

For context we were going about the process of bringing our pack to 1.19.1 last night and going through our mod listings of 356 current mods in 1.18.2. When your mod was (and currently still does as this posting) searched for it showed that version as compatible. 

![Screenshot 2022-07-31 122533](https://user-images.githubusercontent.com/98628933/182036052-14a1ac5e-0adb-434f-a072-21301877a977.png)

![Screenshot 2022-07-31 122725](https://user-images.githubusercontent.com/98628933/182036057-b7c0295b-f2c0-491a-854e-69241e2cceab.png)

**Comment by Lightman314** [comment]
My apologies if my response seemed "defensive", but I have received many issue reports in the past reporting issues that have already long been fixed, or were issues caused by other mods and had nothing to do with mine. Combine that with the fact that I had limited time to look into this as I had to leave shortly after I saw the issue report I didn't have time to fully research the issue.

Also, for future reference. As a general rule, we mod developers do not have the time to check every minor thing (especially things like whether it was flagged correctly on curseforge, as that doesn't affect whether the mod actually works or not) every time an issue is reported, so when we look over issue reports to determine if it's a major enough issue to put our time into, we generally only have the info provided by the person reporting the issue, so you not mentioning that the file was flagged a 1.19,1 build is a _**very important**_ piece of info that you failed to provide, and thus, using only the info that **_you_** provided, this issue appeared to be a "please update to 1.19.1" plea at best, and just plain user-error at worst.

That said, thank you for eventually providing the info that this file was incorrectly flagged as being compatible with 1.19.1, I have gone through and double-checked and confirmed that none of my builds are flagged as 1.19.1, so this issue has now been fixed.

**Comment by HarryPlopper91** [comment]
Yes, at the original posting time I had not considered it could have been tagged incorrectly, so i did not include that. Having thought that it was uploaded intentionally for 1.19.1 originally, i figured this might have been a new issue and was only trying to help. It does give some pause however to future bug reporting to you. I write mobile apps and take every report seriously and dig into each one to verify everything on my end is correct before i comment or respond to any bug reports. Down side of a text or comment is there is no emotion to it so words can be taken out of context or not as intended. Do look forward to seeing it come to 1.19.1 if that is your plan.

**Comment by Lightman314** [comment]
While I understand your concern about me not taking every report seriously, I often receive issue reports from children that don't even understand the basic concepts of how Minecraft works (such as #26, which they shortly harassed me about on discord, which is why there's no actual conversation on the ticket itself), whereas in a professional environment, issue reports come from adults working in a development related field, or at the very least work in some sort of professional environment.

Also, keep in mind that I'm not a professional developer, I'm just some dude who likes to dabble in Minecraft modding in my free time, it's hardly fair to hold me to professional standards. You may be used to working with professionals, but it's far from "professional" to call me "defensive" and saying I'm "acting like a child" based off of a single comment where I simply just listed the facts as to why I deemed the issue a non-issue.

I will admit, I should have asked more questions, like "why would you think it would work in the first place?" and waited for a response before actually closing the ticket, but in my defense, I had only just woken up and wanted to get it taken care of before I left 5 minutes later.

As for getting a 1.19.1 version working, I tested a few of the latest versions for 1.19 and they do appear to work with forge 42.0.1, so I flagged them as 1.19.1 compatible on curseforge. If you encounter any issues with those, you're more than welcome to report them, but from what I know about what mojang changed in 1.19.1, there shouldn't be anything that affects my mod, so I find the changes of any issues arising low.

**Comment by HarryPlopper91** [comment]
Your good man, I get it. I dont work professionally in the field either. Education in it but not my current career. Kids are fun to deal with 😆. Keep doing the good work, happy to have future conversations with you about it, think we just had a misunderstanding and it happens, no worries.
