### ISSUE TITLE
BUG: {insert description here}

### ISSUE THREAD

**Issue by huganug** [Lightman314/LightmansCurrency#82]
Minecraft Version (REQUIRED): 1.19.2
Forge Version (REQUIRED):  43.1.1
Lightman's Currency Version (REQUIRED):  1.19.2 (I just downloaded the new update)
Other Relevant Mods & Version (LC Tech, etc.): 
Connection Type (Single-player, server/client, LAN world): mcprohosting server

**Describe the bug**
All textures for the different items are wrong. I try to place an ATM but the netherite coin pile is what appears. I can still right click to access the ATM but its a pile a netherite coins instead of the actual ATM. This is the same for all other placeable items like the coin mint.

**To Reproduce**
1. place an item
2. see error
**Expected behavior**
I expected the ATM to appear when I placed the ATM. 

**Screenshots/Logs/Crash Reports**
![2022-08-29_21 57 54](https://user-images.githubusercontent.com/112293678/187331872-34a78d8b-6605-4ee3-99d2-f59f76b41256.png)

**Comment by Lightman314** [comment]
I have no clue as to why this would ever happen, as the models/block states are stored in a resource pack format within the jar file, so no amount of coding screw-ups could ever cause this to happen (short of re-writing the vanilla rendering code, which I very much didn't).

I tested it in 1.19.2 as well (forge 43.1.3) in a single-player world, and the ATM had the proper model, etc.
![image](https://user-images.githubusercontent.com/4554273/187334415-ca8ea514-c407-43a2-b767-2e3d5704813d.png)

Either your resources got loaded incorrectly due to some weird error (which you can probably fix with F3 + T, or just rebooting the game), or you've got some other mod that's screwing things up for some odd reason.

**Comment by huganug** [comment]
Thanks for getting back to me, after some testing I eventually got your mod to work properly. I found that it has some weird incompatibility with the Ars Nouveau mod. So I guess if anyone has the same issue that might be the problem.  Thanks for helping me! From: LightmanSent: Monday, August 29, 2022 10:25 PMTo: Lightman314/LightmansCurrencyCc: huganug; AuthorSubject: Re: [Lightman314/LightmansCurrency] BUG: {insert description here} (Issue #82) I have no clue as to why this would ever happen, as the models/block states are stored in a resource pack format within the jar file, so no amount of coding screw-ups could ever cause this to happen (short of re-writing the vanilla rendering code, which I very much didn't).I tested it in 1.19.2 as well (forge 43.1.3) in a single-player world, and the ATM had the proper model, etc.Either your resources got loaded incorrectly due to some weird error (which you can probably fix with F3 + T, or just rebooting the game), or you've got some other mod that's screwing things up for some odd reason.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
