### ISSUE TITLE
Add support for Thermal Expansion

### ISSUE THREAD

**Issue by DaryanTSNS** [Lightman314/LightmansCurrency#87]
My modpack has Thermal Expansion, but I don't see a datapack that adds support for Thermal Expansion Copper Ingots. Also, would it be possible for the Copper Coin Mint recipes to instead use Ore Dictionary?

**Comment by Lightman314** [comment]
First off, I'm assuming you're using the 1.16 version of the mod, as this would otherwise be a non-issue.

Second off, the ore dictionary has not existed since mojang added item/block tags, as those are now used instead.

Third off. While I could theoretically use the item tag for copper to mint copper ingots into copper coins, it's not possible to do so in the other direction, as the output must be a single & specific item, not an item tag that could contain anywhere from 0 items to 1 million items.

That said. If you could provide me with the thermal expansion's copper ingot item id, I could easily whip up a data pack to get the TE copper ingots mintable.

**Comment by DaryanTSNS** [comment]
I think the item ID for the Copper Ingot from Thermal Expansion is "thermal:copper_ingot", does that look right? Also, I was referring specifically to the item tag for the input item in the recipes where the Copper Ingots get turned into Copper Coins.

**Comment by Lightman314** [comment]
Tinker's added their own copper ingot in the last 1.16 build I played, that said it's possible that they disable it if they detect another mod that adds their own copper.

As for using the item tag for the mint recipe, I probably could do that easily enough, but I've stopped supporting 1.16 ages ago so I don't really wanna release a new build after all this time just to add one recipe file that can be made in literally 10 seconds by anyone who wants to. That and then I'd have people reporting that the config option to let players melt copper coins isn't working despite the copper minting working just fine, and that's a whole other can of worms that I don't want to open.

Anyways, the new Thermal Expansion compatibility data pack has been uploaded, and can now be downloaded [here](https://github.com/Lightman314/LightmansCurrency/tree/LC-1.16/Recipe%20Datapacks)!
