### ISSUE TITLE
Feature Request: distribution of fashion on the site curseforge.com

### ISSUE THREAD

**Issue by PhantomX5571** [Lightman314/LightmansCurrency#97]
Hello, I wanted to offer you a little bit to improve the distribution of this mod on the Internet.
It would be very nice if this mod could be downloaded from the website curseforge.com. And also I have a question from myself how do I download on the website github.com the java mod itself and not the source code as a zip archive

**Comment by Lightman314** [comment]
1- The mod can be already be downloaded from curseforge (https://www.curseforge.com/minecraft/mc-mods/lightmans-currency). If you are for any reason unable to download it from curseforge, then that would be an issue with curseforge itself, and is beyond my control.

2- It is **not** possible to download the mod jar from github, nor will it ever be. The main purpose of the github page is to host the source code to the general public so that other mod developers can view the my mods source code for various reasons (looking up how to make an addon, see what part of code is causing a conflict, etc.), with it's secondary purpose being a place for users to report issues or request features/translations. Github is *not*, however, where the mod itself it posted for download for the general public, for that you should be going to the curseforge page (linked above), or using the curseforge app/launcher.
